POST http://localhost:3003/api/users
Content-Type: application/json

# {
#     "username": "jakousa",
#     "name": "Jami Kousa",
#     "password": "jakousa",
#     "disabled": true
# }

# {
#     "username": "mluukkai",
#     "name": "Matti Luukkainen",
#     "password": "mluukkai"
# }

# {
#     "username": "lynx",
#     "name": "Kalle Ilves",
#     "password": "lynx"
# }

# {
#     "username": "root",
#     "name": "root",
#     "password": "root",
#     "admin": true
# }

# {
#     "username": "admin",
#     "name": "Admin",
#     "password": "admin",
#     "admin": true
# }