# POST http://localhost:3003/api/blogs
# Content-Type: application/json
# # Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pbmd4IiwiaWQiOiI2MTFiYWU3NzM1ZTg2NjQ1YmMwNGEyZjQiLCJpYXQiOjE2Mjk0NTczOTMsImV4cCI6MTYyOTQ2MDk5M30.v9IE44VpYOILUjX7CTxpw32jx49Il2Ivb6fGzLVfAPM

# {
#     "author": "great hello",
#     "title": "The Great hello",
#     "url": "http://thegreathello.com",
#     "likes": 123
# }

POST http://localhost:3003/api/blogs
Content-Type: application/json
# Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pbmd4IiwiaWQiOiI2MTFiYWU3NzM1ZTg2NjQ1YmMwNGEyZjQiLCJpYXQiOjE2Mjk0NTczOTMsImV4cCI6MTYyOTQ2MDk5M30.v9IE44VpYOILUjX7CTxpw32jx49Il2Ivb6fGzLVfAPM

{
    "author": "great hello",
    "test": "this is a wrong post field"
}