POST http://localhost:3003/api/users
Content-Type: application/json

# {
#     "username": "admin@admin.com",
#     "name": "admin",
#     "password": "admin"
# }

{
    "username": "root@root.com",
    "name": "root",
    "password": "root"
}



# POST http://localhost:3003/api/users
# Content-Type: application/json

# {
#     "username": "admin",
#     "name": "admin",
#     "password": "admin"
# }s