# DELETE http://localhost:3003/api/blogs/611bb92869757a2c9ccb6d55
# Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pbmd4IiwiaWQiOiI2MTFiYWU3NzM1ZTg2NjQ1YmMwNGEyZjQiLCJpYXQiOjE2Mjk0NjA4ODksImV4cCI6MTYyOTQ2NDQ4OX0.u7hG2LvDY9Kn8qHKx8axCE3P5NArqdCMdRhLSKzUsVE

DELETE http://localhost:3003/api/blogs/3
# Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluQGFkbWluLmNvbSIsImlkIjoxLCJpYXQiOjE3MDYzNjU2MzN9.eii2iaQIsUgSSro2DXSglmr_YsUYOsKPtW_cuhRgJMA
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3RAcm9vdC5jb20iLCJpZCI6MiwiaWF0IjoxNzA2MzY1NDkyfQ.Gz8ZOynL-0MKra8tWyLAHlg9hP_EisTPhQKEIhpVeHY