version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 8080:8080
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
    volumes:
      - ./bloglist/models/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: