version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      # - ./models/init.sql:/docker-entrypoint-initdb.d/init.sql
      - /postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: